"use client";
import {useState} from "react";
import SiteHeader from "../../components/SiteHeader";

const styles=[
 {id:"position",name:"ポジション",hold:"数週間〜数か月",screen:"週1〜数回",noise:"小さい",cost:"少ない",fit:"学業や仕事と両立し、企業・経済をじっくり見たい",risk:"決算や週末をまたぐ急変"},
 {id:"swing",name:"スイング",hold:"数日〜数週間",screen:"1日1〜2回",noise:"中",cost:"中",fit:"日足中心で、ルールを考える時間を確保できる",risk:"翌日の窓開け・材料急変"},
 {id:"day",name:"デイトレード",hold:"数分〜当日中",screen:"取引中は継続",noise:"大きい",cost:"多い",fit:"取引時間を固定し、即座に損切りできる",risk:"判断疲れ・過剰売買・短期の大損"},
 {id:"scalp",name:"スキャルピング",hold:"数秒〜数分",screen:"常時",noise:"非常に大きい",cost:"非常に多い",fit:"高い操作精度と検証経験がある",risk:"初心者には非推奨。コストとミスが結果を支配"},
];
const plans=[
 {id:"pullback",name:"トレンドの押し目",scene:"高値・安値を切り上げ、上向き移動平均線の上にある",pattern:"hammer",patternName:"下ヒゲ反転",confirm:"支持線＋上向き移動平均線＋出来高回復",entry:"支持線付近で下ヒゲが出て、次の足が高値を超えた後",stop:"反転足または直近安値の下",exit:"前回高値、損益比、安値切り下げ",trap:"横ばい相場で押し目だと思い続ける"},
 {id:"breakout",name:"レンジ上抜け",scene:"何度も止められた抵抗線の下で値幅が縮む",pattern:"breakout",patternName:"大陽線＋出来高",confirm:"終値で抵抗線超え＋平均以上の出来高",entry:"抜けた足の確定後、または戻りが抵抗線で支えられた時",stop:"抜けた価格帯へ明確に戻った位置",exit:"レンジ幅の目標、勢い低下、損益比",trap:"ヒゲだけの上抜けや出来高のない『だまし』"},
 {id:"range",name:"レンジ下限の反発",scene:"水平な支持線と抵抗線の間を往復している",pattern:"engulf",patternName:"包み足",confirm:"支持線＋RSIの行き過ぎ解消＋反転足",entry:"支持線で陽の包み足が確定した後",stop:"支持線と包み足の安値の下",exit:"レンジ中央または上限",trap:"強い下落トレンドに逆らって買い続ける"},
 {id:"ma",name:"移動平均線クロス",scene:"長い横ばい後に価格と短期線が長期線を上回る",pattern:"cross",patternName:"小さな足から拡大",confirm:"線の交差＋高値更新＋出来高増加",entry:"交差だけでなく価格構造の上向きを確認した後",stop:"直近安値または長期線の下",exit:"逆クロスでは遅い場合があるため、安値切り下げも使う",trap:"レンジで交差を繰り返し損切りが続く"},
];
function Pattern({type}:{type:string}){return <div className={`pattern-visual ${type}`} aria-label="ローソク足パターン図"><div className="level"/><div className="pv-candles"><i/><i/><i/><i/><i/></div><span>価格の流れ →</span></div>}

export default function MethodsPage(){const[style,setStyle]=useState("swing");const[plan,setPlan]=useState("pullback");const s=styles.find(x=>x.id===style)!;const p=plans.find(x=>x.id===plan)!;return <main className="deep-page methods-page"><SiteHeader current="courses" />
<section className="deep-hero methods-hero"><p className="eyebrow">03 · METHOD &amp; STRATEGY</p><h1>勝てそうな手法より、<br/><em>続けられる手法。</em></h1><p>トレード手法は生活時間、判断回数、コスト、耐えられる損失から選びます。短い時間足ほど簡単になるわけではありません。</p></section>
<section className="method-premise"><div className="deep-heading"><p className="eyebrow">BEFORE STRATEGY</p><h2>戦略の前提は、<br/>6つを一組にすること。</h2></div><div>{["対象商品","時間軸","相場の状態","エントリー条件","損切り条件","利益確定・記録"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><p>「移動平均線が交差したら買う」だけでは戦略ではありません。損切りと使わない相場まで決めて、初めて検証できます。</p></section>
<section className="style-finder"><div className="deep-heading"><p className="eyebrow">FIND YOUR STYLE</p><h2>4つの取引スタイル</h2><p>大学生が授業やアルバイトと両立するなら、まずポジションかスイングが現実的です。</p></div><div className="style-tabs">{styles.map(x=><button className={style===x.id?"active":""} onClick={()=>setStyle(x.id)} key={x.id}>{x.name}<small>{x.hold}</small></button>)}</div><div className="style-sheet"><header><small>SELECTED STYLE</small><h3>{s.name}</h3><b>{s.hold}</b></header><dl><div><dt>画面を見る頻度</dt><dd>{s.screen}</dd></div><div><dt>ノイズ</dt><dd>{s.noise}</dd></div><div><dt>取引コスト</dt><dd>{s.cost}</dd></div><div><dt>向いている人</dt><dd>{s.fit}</dd></div><div><dt>主なリスク</dt><dd>{s.risk}</dd></div></dl></div><p className="risk-alert">短期売買は大きな損失を短時間で生む可能性があります。最初は現物・模擬取引・少ない判断回数を基本にします。</p></section>
<section className="strategy-library"><div className="deep-heading"><p className="eyebrow">REPRESENTATIVE STRATEGIES</p><h2>代表的な4戦略を、<br/>ルールで比べる。</h2><p>図は学習用の概念図です。同じ形が出ても利益を保証せず、特定銘柄の売買を勧めません。</p></div><div className="plan-tabs">{plans.map(x=><button className={plan===x.id?"active":""} onClick={()=>setPlan(x.id)} key={x.id}>{x.name}</button>)}</div><div className="plan-sheet"><div className="plan-visual"><Pattern type={p.pattern}/><span>{p.patternName}</span><p>一本の形ではなく、出現場所と次の足を確認します。</p></div><div className="plan-rules"><h3>{p.name}</h3><dl><div><dt>使う相場</dt><dd>{p.scene}</dd></div><div><dt>組み合わせる確認</dt><dd>{p.confirm}</dd></div><div><dt>エントリー</dt><dd>{p.entry}</dd></div><div><dt>損切り</dt><dd>{p.stop}</dd></div><div><dt>出口</dt><dd>{p.exit}</dd></div><div><dt>弱点・使わない場面</dt><dd>{p.trap}</dd></div></dl></div></div></section>
<section className="position-school"><div className="deep-heading"><p className="eyebrow">POSITION MANAGEMENT</p><h2>建玉は、持っている取引と<br/>背負っているリスク。</h2><p>買った数量だけでなく、どこで損切りするといくら失うかまでを一組で管理します。</p></div><div className="position-example"><header><span>数字で確認</span><h3>資金10万円・最大損失1％</h3></header><div><p><b>損失上限</b>1,000円</p><p><b>買値</b>1,000円</p><p><b>損切り</b>980円</p><p><b>1株のリスク</b>20円</p><strong>1,000円 ÷ 20円 ＝ 最大50株</strong></div></div><div className="position-grid"><article><b>買い建玉・売り建玉</b><p>上昇で利益を狙う保有が買い建玉、下落で利益を狙う保有が売り建玉。売り建玉は損失が拡大する方向を必ず理解します。</p></article><article><b>分割エントリー</b><p>最初から全量を入れず、条件確認ごとに分けます。ただし合計の最大損失は注文前に固定します。</p></article><article><b>ナンピンとの違い</b><p>事前計画のない買い増しは、損失を認めたくない感情になりやすい。追加価格・回数・総損失を先に決めた場合だけ検証できます。</p></article><article><b>建値へ移す</b><p>損切り価格を買値へ上げれば損失を抑えられますが、通常の揺れで早く決済される欠点もあります。</p></article></div></section>
<section className="expectancy-lab"><div className="deep-heading"><p className="eyebrow">EXPECTANCY</p><h2>勝率より、<br/>一回あたりの期待値。</h2><p>勝つ回数だけで手法を評価すると、少ない大損を見落とします。</p></div><div className="expectancy-formula"><p><b>勝率40％ × 平均利益3,000円</b></p><span>−</span><p><b>負け率60％ × 平均損失1,000円</b></p><span>＝</span><strong>＋600円／回</strong></div><p>これは過去の記録から求める平均で、次の取引の利益を保証する数字ではありません。手数料・スプレッド・税金も差し引き、十分な回数で見直します。</p><div className="loss-streak"><h3>連敗に耐えられる損失額にする</h3><p>資金10万円で1回の損失を1％に抑え、5回連続で負けると約9万5,100円。毎回10％を失う設定なら約5万9,000円まで減ります。予想より先に、退場しにくい大きさを決めます。</p></div></section>
<section className="rule-builder"><p className="eyebrow">BUILD YOUR RULE</p><h2>自分のルールを書く</h2><div>{["私は［商品］を［時間足］で見る。","［相場の状態］の時だけ使う。","［3つの根拠］がそろったら入る。","1回の最大損失は資金の［　］％。","［価格・条件］で損切りする。","［価格・条件］で利益確定する。","結果ではなく、ルールを守れたか記録する。"].map(x=><p key={x}>□ {x}</p>)}</div></section>
<section className="source-strip"><span>リスク確認・内容確認 2026年8月14日</span><a href="https://www.investor.gov/additional-resources/spotlight/formerdirectorlorischock-directors-take/thinking-day-trading-know-risks" target="_blank" rel="noreferrer">Investor.gov｜Day Trading Risks ↗</a></section></main>}
