import SiteHeader from "../../components/SiteHeader";

const assets = [
  { id:"stocks", no:"01", name:"個別株", catch:"会社の成長や価値に投資する", fit:"企業を調べ、自分で銘柄を選びたい人", source:"企業利益の成長、配当、市場評価の変化", move:"決算、業績予想、金利、景気、需給", risk:"倒産・業績悪化・一社集中・価格変動", data:["売上高・営業利益・1株利益（EPS）の推移","会社予想と市場の期待との差","営業キャッシュフロー・自己資本比率","PER・PBR・ROEを同業他社と比較","株価・出来高・決算発表日"], first:"まず決算短信の売上・利益・会社予想を前年と比べる。" },
  { id:"funds", no:"02", name:"投資信託・ETF", catch:"複数の資産をまとめて持つ", fit:"少額・分散・長期を仕組み化したい人", source:"中に入っている株式・債券等の値動き", move:"連動指数、組入資産、為替、金利", risk:"元本割れ・指数偏重・為替・商品の構造", data:["何の指数・資産に連動するか","国・業種・上位銘柄への集中度","信託報酬など継続費用","純資産総額・売買高・乖離率","為替ヘッジの有無"], first:"商品名より先に、目論見書の投資対象と費用を見る。" },
  { id:"fx", no:"03", name:"FX", catch:"2つの通貨の交換比率を取引する", fit:"経済指標を追い、短期の値動きを管理できる人", source:"通貨間の金利差と為替レートの変化", move:"政策金利、物価、雇用、景気、政治", risk:"レバレッジ・急変・窓開け・スプレッド拡大", data:["中央銀行の政策金利と声明","CPI・雇用統計・GDP","市場予想と発表値の差","通貨ペアの金利差","経済指標の発表時刻と値幅"], first:"数字の良し悪しではなく、市場予想との差と発表後の反応を見る。" },
  { id:"metals", no:"04", name:"金・銀", catch:"通貨以外の価値保存・商品需要を取引する", fit:"株や通貨と異なる要因を持つ資産を学びたい人", source:"需給、実質金利、通貨価値への評価", move:"米ドル、実質金利、中央銀行需要、鉱山供給", risk:"利息・配当なし、価格変動、商品ごとの費用", data:["米ドル指数と実質金利","中央銀行・ETFの保有動向","鉱山供給と産業需要","金銀比価（ゴールド・シルバー・レシオ）","先物市場のポジション動向"], first:"『不安なら金が上がる』と決めつけず、ドルと実質金利も確認する。" },
  { id:"crypto", no:"05", name:"暗号資産", catch:"ネットワーク上の希少性と利用価値を取引する", fit:"大きな変動と保管リスクを理解して少額で学べる人", source:"需要、供給、ネットワーク利用、期待", move:"規制、資金流入、技術更新、市場心理", risk:"極端な変動・取引所・秘密鍵・規制・流動性", data:["現物出来高と市場の流動性","供給量・発行ルール・保有集中","ネットワーク利用と手数料","規制・上場・技術更新","株式市場など全体のリスク選好"], first:"価格だけでなく、保管先と取引所のリスクを分けて考える。" },
];

export default function ProductsPage(){return <main className="deep-page"><SiteHeader current="courses" />
<section className="deep-hero products-hero"><p className="eyebrow">01 · PRODUCTS &amp; DATA</p><h1>値上がりしそう、ではなく<br/><em>仕組みから選ぶ。</em></h1><p>商品によって、利益が生まれる理由も見るデータも違います。最初は「何にお金を出し、何が起きると損をするか」を説明できる商品だけを候補にします。</p><nav>{assets.map(a=><a href={`#${a.id}`} key={a.id}>{a.name}</a>)}</nav></section>
<section className="product-compare"><div className="deep-heading"><p className="eyebrow">QUICK COMPARE</p><h2>最初の比較軸</h2></div><div className="compare-scroll"><table><thead><tr><th>商品</th><th>主な利益の源泉</th><th>主なリスク</th><th>初心者の基本</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><th>{a.name}</th><td>{a.source}</td><td>{a.risk}</td><td>{a.id==="funds"?"現物・分散・低コスト":a.id==="stocks"?"現物・少額・一社集中を避ける":"まず模擬取引。レバレッジを急がない"}</td></tr>)}</tbody></table></div></section>
<section className="asset-lessons">{assets.map(a=><article id={a.id} className="asset-lesson" key={a.id}><header><span>{a.no}</span><div><p>{a.catch}</p><h2>{a.name}</h2></div></header><div className="asset-body"><div className="asset-basics"><dl><div><dt>向いている人</dt><dd>{a.fit}</dd></div><div><dt>利益が生まれる理由</dt><dd>{a.source}</dd></div><div><dt>価格が動く主因</dt><dd>{a.move}</dd></div><div><dt>主なリスク</dt><dd>{a.risk}</dd></div></dl></div><div className="asset-data"><span>最初に見る5つのデータ</span><ol>{a.data.map(x=><li key={x}>{x}</li>)}</ol><p><b>最初の一歩</b>{a.first}</p></div></div></article>)}</section>
<section className="decision-gate"><p className="eyebrow">DECISION GATE</p><h2>商品を選ぶ前の5問</h2><div>{["利益が生まれる理由を説明できる？","最大でどれくらい下がり得る？","現物か、レバレッジ商品か？","必要な情報を継続して確認できる？","使う予定のない余裕資金だけ？"].map((q,i)=><p key={q}><b>{i+1}</b>{q}</p>)}</div><a href="/strategies/chart">次はチャートの読み方へ →</a></section></main>}
