"use client";
import {useMemo,useState} from "react";
import SiteHeader from "../../components/SiteHeader";

export default function LeveragePage(){const[capital,setCapital]=useState(100000);const[multiple,setMultiple]=useState(5);const[move,setMove]=useState(-5);const exposure=capital*multiple;const pnl=Math.round(exposure*move/100);const after=capital+pnl;const capitalMove=Math.round((pnl/capital)*1000)/10;return <main className="leverage-page">
  <SiteHeader current="mechanics" />
  <section className="leverage-hero"><p className="eyebrow">LEVERAGE · THE FULL MECHANISM</p><h1>何倍儲かるかではなく、<br/><em>何円分の値動きを背負うか。</em></h1><p>レバレッジとは、預けた資金より大きい取引金額の損益を引き受ける仕組みです。借りた現金を受け取るとは限りません。まず証拠金・取引金額・損益を分けます。</p></section>
  <section className="leverage-core"><div className="deep-heading"><p className="eyebrow">THE THREE NUMBERS</p><h2>混同してはいけない3つ</h2></div><div><article><span>01</span><h3>口座資金</h3><p>自分が口座へ入れたお金。損失を受け止める土台。</p></article><article><span>02</span><h3>証拠金</h3><p>取引の担保として必要な金額。商品の代金ではない。</p></article><article><span>03</span><h3>取引金額</h3><p>実際に価格変動の影響を受ける金額。損益はこれに対して発生。</p></article></div><div className="leverage-formula"><b>実効レバレッジ</b><span>取引金額</span><i>÷</i><span>口座資金</span><i>＝</i><strong>何倍</strong></div></section>
  <section className="why-possible"><div className="deep-heading"><p className="eyebrow">WHY IT WORKS</p><h2>なぜ全額を払わず、<br/>大きな取引ができる？</h2></div><p>現物では50万円分を買うなら原則50万円を支払います。FX・CFD・先物などでは、開始価格と終了価格の差額を清算する仕組みが使われます。50万円の商品を受け取って保管するのではなく、50万円分の値動きによる損益をやり取りします。</p><div className="difference-flow"><span>50万円分で開始</span><i>価格が5％上昇</i><span>52万5,000円相当</span><strong>差額<br/>＋2万5,000円</strong></div><p>取引会社は損失に備える担保を求めます。それが証拠金です。証拠金10万円で50万円分を取引すれば5倍ですが、50万円をもらったわけではありません。50万円分の価格変動責任を引き受けています。</p></section>
  <section className="leverage-calculator"><div className="deep-heading"><p className="eyebrow">MOVE THE NUMBERS</p><h2>倍率と値動きで、<br/>資金への影響を見る。</h2><p>教育用の単純計算です。手数料、スプレッド、金利、税金、約定ずれは含みません。</p></div><div className="calc-grid"><div className="calc-controls"><label><span>口座資金</span><input type="range" min="10000" max="500000" step="10000" value={capital} onChange={e=>setCapital(Number(e.target.value))}/><b>{capital.toLocaleString()}円</b></label><label><span>実効レバレッジ</span><input type="range" min="1" max="25" step="1" value={multiple} onChange={e=>setMultiple(Number(e.target.value))}/><b>{multiple}倍</b></label><label><span>価格の変化</span><input type="range" min="-10" max="10" step="1" value={move} onChange={e=>setMove(Number(e.target.value))}/><b>{move>0?"+":""}{move}%</b></label></div><div className={`calc-result ${pnl<0?"loss":"gain"}`}><div><span>取引金額</span><strong>{exposure.toLocaleString()}円</strong></div><div><span>損益</span><strong>{pnl>0?"+":""}{pnl.toLocaleString()}円</strong></div><div><span>資金への影響</span><strong>{capitalMove>0?"+":""}{capitalMove}%</strong></div><p>計算後の資金：{after.toLocaleString()}円</p></div></div></section>
  <section className="leverage-table"><div className="deep-heading"><p className="eyebrow">SAME MOVE, DIFFERENT DAMAGE</p><h2>価格が5％動いた場合</h2></div><div className="compare-scroll"><table><thead><tr><th>資金</th><th>倍率</th><th>取引金額</th><th>＋5％</th><th>−5％</th></tr></thead><tbody>{[1,2,5,10,25].map(x=><tr key={x}><td>10万円</td><th>{x}倍</th><td>{(100000*x).toLocaleString()}円</td><td>＋{(5000*x).toLocaleString()}円</td><td>−{(5000*x).toLocaleString()}円</td></tr>)}</tbody></table></div><p>25倍なら4％の逆行で、計算上は元の10万円と同額の損失です。実際にはそれより前にロスカットされる場合がありますが、急変時には元手を超える損失もあり得ます。</p></section>
  <section className="margin-system"><div className="deep-heading"><p className="eyebrow">MARGIN SYSTEM</p><h2>最低必要額と、<br/>耐えられる資金は違う。</h2></div><div className="mechanics-copy"><p>必要証拠金率4％の商品を100万円分取引するなら、計算上の必要証拠金は4万円です。しかし4万円だけを入れると、小さな逆行で余力がなくなります。「最低限取引できる金額」は「安全に続けられる金額」ではありません。</p><div className="formula-card"><span>有効証拠金</span><i>÷</i><span>必要証拠金</span><i>× 100</i><strong>証拠金維持率</strong></div><p>口座資金10万円、含み損2万円なら有効証拠金は8万円。必要証拠金4万円なら維持率は200％です。計算方法や追加証拠金・ロスカットの基準は商品と取引会社で異なります。</p></div></section>
  <section className="loss-chain"><div className="deep-heading"><p className="eyebrow">WHEN PRICE MOVES AGAINST YOU</p><h2>含み損から強制決済まで</h2></div><ol><li><span>01</span><b>価格が逆行</b><p>取引金額に対して含み損が発生。</p></li><li><span>02</span><b>有効証拠金が減る</b><p>口座資金から含み損を差し引いた余力が低下。</p></li><li><span>03</span><b>追証・入金要求</b><p>基準を下回ると追加資金が必要になる場合がある。</p></li><li><span>04</span><b>ロスカット</b><p>一定水準で取引会社が強制的に決済。</p></li></ol><div className="mechanics-note"><b>ロスカットは損失保証ではない</b><p>急変、週明けの価格差、流動性低下などで予定価格から離れて約定し、預けた金額以上の損失が残ることがあります。</p></div></section>
  <section className="risk-sizing"><div className="deep-heading"><p className="eyebrow">SIZE FROM RISK</p><h2>倍率ではなく、<br/>許容損失から数量を決める。</h2></div><div className="mechanics-copy"><p>口座資金10万円で、1回の許容損失を1,000円とします。損切りまで2％なら、取引金額は5万円です。</p><div className="risk-equation"><span>許容損失 1,000円</span><i>÷</i><span>損切り幅 2％</span><i>＝</i><strong>取引金額 5万円</strong></div><p>実効レバレッジは0.5倍です。最大25倍まで使えることと、25倍を使うべきことは別です。先に「負けたら何円か」を決め、その範囲に収まる取引量を逆算します。</p></div></section>
  <section className="mental-cost"><p className="eyebrow">THE HIDDEN COST</p><h2>高い倍率は、判断力にも<br/>レバレッジをかける。</h2><div><p>損切りを遅らせる</p><p>利益を早く確定する</p><p>取り返すため金額を増やす</p><p>取引中にルールを変える</p></div><blockquote>レバレッジは、少ない資金で儲ける道具ではない。<br/><em>許容損失の範囲で取引金額を管理する仕組み。</em></blockquote></section>
  <section className="source-strip"><span>一次資料</span><a href="https://www.ffaj.or.jp/" target="_blank" rel="noreferrer">金融先物取引業協会｜FXの制度と学習 ↗</a><a href="https://www.jpx.co.jp/derivatives/products/domestic/225mini/index.html" target="_blank" rel="noreferrer">JPX｜日経225miniの仕組み ↗</a><a href="https://www.jpx.co.jp/jscc/seisan/sakimono/shokokin_seido/shokokin.html" target="_blank" rel="noreferrer">JSCC｜先物の証拠金制度 ↗</a></section>
 </main>}
