import SiteHeader from "../../components/SiteHeader";
import PatternDiagram from "../../components/PatternDiagram";

const indicators=[
 {no:"01",name:"出来高",role:"参加量を見る",what:"一定期間に成立した取引量。値動きにどれだけ参加が伴っているかを見る。",use:"抵抗線を抜ける時に平均より増えているか、上昇中に減っていないか。",weak:"出来高だけでは買いと売りのどちらが優勢か確定できない。FXの出来高は市場全体ではない場合がある。",pair:"価格・支持線／抵抗線"},
 {no:"02",name:"移動平均線（SMA・EMA）",role:"方向を見る",what:"過去の終値を平均し、価格の細かな揺れをならした線。EMAは直近価格をより重くする。",use:"線の傾き、価格との位置、短期線と長期線の並びを見る。",weak:"過去データなので遅れる。横ばいでは交差が増え、だましが多い。",pair:"高値・安値の方向、出来高"},
 {no:"03",name:"RSI",role:"勢いを見る",what:"直近の上昇と下落の強さを0〜100で表す。一般に70超・30未満が注目される。",use:"レンジの端で行き過ぎと反転を確認する。価格との逆行も補助材料。",weak:"強いトレンドでは70超・30未満に長く留まる。数値だけで逆張りしない。",pair:"支持線／抵抗線、反転足"},
 {no:"04",name:"MACD",role:"流れの変化を見る",what:"期間の異なるEMAの差と、その平均線を使って勢いの変化を表す。",use:"ゼロラインの上下、MACDとシグナルの交差、ヒストグラムの拡大・縮小。",weak:"急変には遅れやすく、レンジでは交差が頻発する。",pair:"上位足のトレンド、価格構造"},
 {no:"05",name:"ボリンジャーバンド",role:"値動きの幅を見る",what:"移動平均線の上下に、標準偏差を使った帯を表示する。帯の拡大・縮小で変動の状態を見る。",use:"縮小後の拡大、トレンド中の帯沿い、レンジの中心線と端を観察。",weak:"上限に触れた＝売り、下限に触れた＝買いではない。強い相場では帯に沿って進む。",pair:"出来高、支持線／抵抗線"},
];

function CandleAnatomy(){return <div className="candle-reference"><img src="/visuals/candlestick-reference.png" alt="緑の陽線とコーラル色の陰線。どちらも実体と上下のヒゲがある"/><div><article><b>陽線</b><p>終値が始値より高い足。実体の下が始値、上が終値です。</p></article><article><b>陰線</b><p>終値が始値より低い足。実体の上が始値、下が終値です。</p></article></div><small>このサイトは陽線＝緑、陰線＝コーラルで統一します。取引サービスによって色が逆の場合があります。</small></div>}

export default function ChartPage(){return <main className="deep-page chart-page"><SiteHeader current="courses" />
<section className="deep-hero chart-hero"><p className="eyebrow">02 · CHART READING</p><h1>チャートに表示される<br/><em>情報と読み方</em></h1><p>チャートは過去の価格と取引の記録です。未来を予言する図ではなく、今どの状態かを同じ手順で判断する道具です。</p></section>
<section className="chart-order"><div className="deep-heading"><p className="eyebrow">READING ORDER</p><h2>チャートを見るときの主な観点</h2><p>以下は初心者が情報を整理するための一例です。取引期間や手法によって、確認する項目や順序は変わります。</p></div><div>{[["01","時間軸","週足・日足で大きな方向を確認"],["02","価格構造","高値と安値が上か下か横ばいか"],["03","重要価格","支持線・抵抗線・前回高安"],["04","ローソク足","買い手と売り手の押し戻し"],["05","出来高","その動きに参加が伴うか"],["06","補助指標","目的に合う1〜2個だけ"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="timeframes"><div className="deep-heading"><p className="eyebrow">TIMEFRAME</p><h2>時間足による見え方の違い</h2></div><div className="timeframe-grid"><article><b>上位足</b><h3>大きな値動きを確認する</h3><p>週足・日足で、大きなトレンドと重要価格を確認します。ここに逆らう取引は難度が上がります。</p></article><article><b>取引足</b><h3>取引に使う時間足を確認する</h3><p>スイングなら日足・4時間足、デイトレなら1時間足・15分足など、自分の保有時間に合わせます。</p></article><article><b>下位足</b><h3>短い時間足の特徴</h3><p>短い足ほどノイズと判断回数が増えます。初心者は1分足を避け、確認する時間足を固定します。</p></article></div></section>
<section className="candle-deep"><div className="deep-heading"><p className="eyebrow">CANDLESTICK</p><h2>ローソク足の見方</h2><p>一本よりも「どこで出たか」「前後に何があるか」を重視します。</p></div><CandleAnatomy/><div className="candle-points"><article><b>実体</b><p>始値と終値の差。長い実体は、その期間に一方向へ強く動いたことを示します。</p></article><article><b>ヒゲ</b><p>高値・安値まで進んだ後、押し戻された範囲。長い下ヒゲは安値で買い戻された記録です。</p></article><article><b>出た場所</b><p>支持線上の下ヒゲと、何もない場所の下ヒゲでは意味が違います。出来高と次の足も確認します。</p></article></div></section>
<section className="line-school"><div className="deep-heading"><p className="eyebrow">DRAWING LINES</p><h2>水平線とトレンドラインの引き方</h2><p>水平線は、過去に価格が何度か止まった範囲へ横向きに引きます。トレンドラインは、上昇時の安値同士、または下降時の高値同士を斜めに結びます。ヒゲ先と実体のどちらを基準にするかを決め、同じ図の中では基準を混ぜません。</p></div><div className="line-grid"><article><PatternDiagram type="lineHorizontal" label="ローソク足上の支持線と抵抗線" compact/><h3>水平線</h3><p>二回以上止まった高値・安値を候補にします。ヒゲ先だけに合わせず、終値が集まる範囲も見ます。</p><strong>点ではなく価格帯として扱う</strong></article><article><PatternDiagram type="lineTrend" label="ローソク足のヒゲ先の安値を結んだ上昇トレンドライン" compact/><h3>トレンドライン</h3><p>この図では、上昇中の安値のヒゲ先を結んでいます。実体の下端で反応がそろう場合は実体を基準にできますが、途中で基準を変えません。</p><strong>ヒゲ先で引く例。二点で仮、三点目で確認</strong></article><article><PatternDiagram type="lineChannel" label="上下のヒゲ先を基準にした平行チャネル" compact/><h3>平行チャネル</h3><p>安値のヒゲ先を結んだ線を基準に、同じ傾きの線を上ヒゲ先へ置きます。この図では、下側は安値のヒゲ先、上側は高値のヒゲ先に合わせています。</p><strong>上下ともヒゲ先基準。同じ傾きを保つ</strong></article></div></section>
<section className="ma-school"><div className="deep-heading"><p className="eyebrow">MA · SMA · EMA</p><h2>移動平均線（MA・SMA・EMA）の違い</h2><p>移動平均線は価格をならして方向を見やすくする遅行指標です。未来を先に示す線ではありません。</p></div><div className="ma-visual"><PatternDiagram type="maCross" label="ローソク足と短期・長期移動平均線"/><div><p><i className="fast-key"/>短期MA</p><p><i className="slow-key"/>長期MA</p></div></div><div className="ma-grid"><article><b>SMA</b><h3>SMAの計算方法</h3><p>例えば20日SMAは直近20日分の終値を合計して20で割ります。動きは比較的なめらかです。</p></article><article><b>EMA</b><h3>EMAの計算方法</h3><p>同じ期間のSMAより直近の変化へ速く反応します。その分、短期の揺れにも反応しやすくなります。</p></article><article><b>組み合わせ</b><h3>移動平均線で確認できること</h3><p>価格が線の上か下か、線が上向きか、短期線と長期線がどう並ぶかを確認します。交差だけでは入りません。</p></article></div></section>
<section className="indicator-lessons"><div className="deep-heading"><p className="eyebrow">SELECTED INDICATORS</p><h2>よく使われる主な指標</h2><p>役割が重なる指標を何個も入れません。「方向・勢い・変動・参加量」から必要なものを選びます。</p></div>{indicators.map(x=><article key={x.no}><header><span>{x.no}</span><div><small>{x.role}</small><h3>{x.name}</h3></div></header><div className="indicator-grid"><div><b>何を表す？</b><p>{x.what}</p></div><div><b>どう使う？</b><p>{x.use}</p></div><div><b>弱点</b><p>{x.weak}</p></div><div><b>組み合わせ</b><p>{x.pair}</p></div></div></article>)}</section>
<section className="chart-case"><div className="deep-heading"><p className="eyebrow">WORKED EXAMPLE</p><h2>チャートを読む例</h2><p>数字は説明用です。形を当てるのではなく、観察と判断を分けます。</p></div><div className="case-timeline">{[["01","日足を見る","高値と安値が切り上がっている。大きな方向は上向き。"],["02","重要価格を引く","過去に3回止められた1,000円を抵抗線とする。"],["03","終値を待つ","一時1,010円まで上がったが、終値は990円。上抜けは未確定。"],["04","出来高を見る","普段より少ない。参加を伴う強い突破とは判断しにくい。"],["05","行動を決める","今回は見送る。終値で1,000円を超え、次の足でも維持できるか待つ。"]].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="worked-story"><h3>抵抗線を一時的に超えた場合</h3><p>取引時間中に抵抗線を超えても、売りに押されて終値が下なら、上ヒゲとして残ります。一本だけで失敗と断定はできませんが、少なくとも「上抜け確定」と急いで買う根拠にはしません。</p></div></section>
<section className="minimum-chart"><p className="eyebrow">MINIMUM SETUP</p><h2>初心者向けの表示例</h2><div><span>価格</span><i>＋</i><span>出来高</span><i>＋</i><span>移動平均線1〜2本</span></div><p>RSI・MACD・ボリンジャーバンドは、戦略上の目的がある時に一つ追加します。全部同時には使いません。</p></section>
<section className="pattern-gateway"><div><p className="eyebrow">NEXT · PATTERN ATLAS</p><h2>主なチャートパターンを確認する</h2><p>ローソク足、反転、継続、ブレイクを図解しました。初心者は「基本」表示のパターンだけで十分です。</p></div><a href="/strategies/patterns">チャートパターン図鑑へ →</a></section>
<section className="source-strip"><span>参考資料・内容確認 2026年8月14日</span><a href="https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/overview" target="_blank" rel="noreferrer">Fidelity Technical Indicator Guide ↗</a><a href="https://www.schwab.com/learn/story/how-to-read-stock-charts-and-trading-patterns" target="_blank" rel="noreferrer">Schwab Chart Reading Guide ↗</a></section></main>}
