const indicators=[
 {no:"01",name:"出来高",role:"参加量を見る",what:"一定期間に成立した取引量。値動きにどれだけ参加が伴っているかを見る。",use:"抵抗線を抜ける時に平均より増えているか、上昇中に減っていないか。",weak:"出来高だけでは買いと売りのどちらが優勢か確定できない。FXの出来高は市場全体ではない場合がある。",pair:"価格・支持線／抵抗線"},
 {no:"02",name:"移動平均線（SMA・EMA）",role:"方向を見る",what:"過去の終値を平均し、価格の細かな揺れをならした線。EMAは直近価格をより重くする。",use:"線の傾き、価格との位置、短期線と長期線の並びを見る。",weak:"過去データなので遅れる。横ばいでは交差が増え、だましが多い。",pair:"高値・安値の方向、出来高"},
 {no:"03",name:"RSI",role:"勢いを見る",what:"直近の上昇と下落の強さを0〜100で表す。一般に70超・30未満が注目される。",use:"レンジの端で行き過ぎと反転を確認する。価格との逆行も補助材料。",weak:"強いトレンドでは70超・30未満に長く留まる。数値だけで逆張りしない。",pair:"支持線／抵抗線、反転足"},
 {no:"04",name:"MACD",role:"流れの変化を見る",what:"期間の異なるEMAの差と、その平均線を使って勢いの変化を表す。",use:"ゼロラインの上下、MACDとシグナルの交差、ヒストグラムの拡大・縮小。",weak:"急変には遅れやすく、レンジでは交差が頻発する。",pair:"上位足のトレンド、価格構造"},
 {no:"05",name:"ボリンジャーバンド",role:"値動きの幅を見る",what:"移動平均線の上下に、標準偏差を使った帯を表示する。帯の拡大・縮小で変動の状態を見る。",use:"縮小後の拡大、トレンド中の帯沿い、レンジの中心線と端を観察。",weak:"上限に触れた＝売り、下限に触れた＝買いではない。強い相場では帯に沿って進む。",pair:"出来高、支持線／抵抗線"},
];

function CandleAnatomy(){return <div className="lesson-candle"><span className="lc-high">高値</span><i className="lc-wick top"/><b/><i className="lc-wick bottom"/><span className="lc-open">始値</span><span className="lc-close">終値</span><span className="lc-low">安値</span></div>}

export default function ChartPage(){return <main className="deep-page chart-page"><header className="topbar site-header"><a className="brand" href="/"><span className="brand-mark">18</span><span>投資の地図</span></a><nav className="global-nav"><a href="/strategies">学習マップ</a><a href="/strategies/products">商品</a><a className="current" href="/strategies/chart">チャート</a><a href="/strategies/methods">戦略</a><a href="/glossary">用語集</a></nav></header>
<section className="deep-hero chart-hero"><p className="eyebrow">02 · CHART READING</p><h1>形を覚える前に、<br/><em>読む順番を覚える。</em></h1><p>チャートは過去の価格と取引の記録です。未来を予言する図ではなく、今どの状態かを同じ手順で判断する道具です。</p></section>
<section className="chart-order"><div className="deep-heading"><p className="eyebrow">READING ORDER</p><h2>毎回この6段階で読む</h2><p>下からではなく、広い時間軸から狭い時間軸へ。指標は最後です。</p></div><div>{[["01","時間軸","週足・日足で大きな方向を確認"],["02","価格構造","高値と安値が上か下か横ばいか"],["03","重要価格","支持線・抵抗線・前回高安"],["04","ローソク足","買い手と売り手の押し戻し"],["05","出来高","その動きに参加が伴うか"],["06","補助指標","目的に合う1〜2個だけ"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="timeframes"><div className="deep-heading"><p className="eyebrow">TIMEFRAME</p><h2>時間足が変われば、<br/>見える相場も変わる。</h2></div><div className="timeframe-grid"><article><b>上位足</b><h3>環境を決める</h3><p>週足・日足で、大きなトレンドと重要価格を確認します。ここに逆らう取引は難度が上がります。</p></article><article><b>取引足</b><h3>入る形を待つ</h3><p>スイングなら日足・4時間足、デイトレなら1時間足・15分足など、自分の保有時間に合わせます。</p></article><article><b>下位足</b><h3>細かくしすぎない</h3><p>短い足ほどノイズと判断回数が増えます。初心者は1分足を避け、確認する時間足を固定します。</p></article></div></section>
<section className="candle-deep"><div className="deep-heading"><p className="eyebrow">CANDLESTICK</p><h2>ローソク足は、<br/>価格の攻防の記録。</h2><p>一本よりも「どこで出たか」「前後に何があるか」を重視します。</p></div><div className="candle-core"><CandleAnatomy/><div><article><b>実体</b><p>始値と終値の差。長い実体は、その期間に一方向へ強く動いたことを示します。</p></article><article><b>ヒゲ</b><p>一度進んだ価格が押し戻された範囲。長い下ヒゲなら、安値で買い戻された事実を示します。</p></article><article><b>形だけでは決めない</b><p>支持線付近の下ヒゲと、何もない場所の下ヒゲは意味が違います。出来高と次の足も確認します。</p></article></div></div></section>
<section className="indicator-lessons"><div className="deep-heading"><p className="eyebrow">SELECTED INDICATORS</p><h2>主要指標は5つで十分。</h2><p>役割が重なる指標を何個も入れません。「方向・勢い・変動・参加量」から必要なものを選びます。</p></div>{indicators.map(x=><article key={x.no}><header><span>{x.no}</span><div><small>{x.role}</small><h3>{x.name}</h3></div></header><div className="indicator-grid"><div><b>何を表す？</b><p>{x.what}</p></div><div><b>どう使う？</b><p>{x.use}</p></div><div><b>弱点</b><p>{x.weak}</p></div><div><b>組み合わせ</b><p>{x.pair}</p></div></div></article>)}</section>
<section className="minimum-chart"><p className="eyebrow">MINIMUM SETUP</p><h2>最初のチャート設定</h2><div><span>価格</span><i>＋</i><span>出来高</span><i>＋</i><span>移動平均線1〜2本</span></div><p>RSI・MACD・ボリンジャーバンドは、戦略上の目的がある時に一つ追加します。全部同時には使いません。</p><a href="/strategies/methods">次は自分に合う手法と戦略へ →</a></section>
<section className="source-strip"><span>参考資料</span><a href="https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/overview" target="_blank" rel="noreferrer">Fidelity Technical Indicator Guide ↗</a><a href="https://www.schwab.com/learn/story/how-to-read-stock-charts-and-trading-patterns" target="_blank" rel="noreferrer">Schwab Chart Reading Guide ↗</a></section></main>}
